# whitelist
branches:
    only:
      - master
      - dev

language: node_js
node_js:
    - node
script:
    - cd functions
    - npm run test:coverage
# deploy:
#     provider: npm
#     email: "$NPM_EMAIL"
#     api_key: "$NPM_TOKEN"
# notifications:
#     email: true