# whitelist
branches:
    only:
      - master
      - dev

language: node_js
node_js:
    - node
jobs:
    include:
        - stage: "Tests"
            name: "Unit Tests Functions"
            before_script: 
                - cd functions
                - npm i
            script: npm run test:coverage
        - name: "Unit Tests Website"
            before_script:
                - cd website
                - npm i
            script: npm run test


# script: npm run test:coverage
# before_script: 
#     - cd functions
#     - npm i
# after_script: cd ..
# before_script:
#     - cd website
#     - npm i
# script: npm run test        

# script:
#     - cd functions
#     - npm run test:coverage
#     - cd ..
#     - cd website
#     - npm run test
# deploy:
#     provider: npm
#     email: "$NPM_EMAIL"
#     api_key: "$NPM_TOKEN"
notifications:
    email: false