sudo: false

branches:
  only:
    - master
    - dev

language: node_js
node_js:
    - node

jobs:
  include:
    - stage: unit tests
      name: Unit Tests Functions
      before_script:
        - cd functions
        - npm i
      script: npm run test:coverage
    - stage: unit tests
      name: Unit Tests Website
      before_script:
        - cd functions
        - npm i
      script: npm run test
