sudo: true
branches:
  only:
  - master
  - dev
language: node_js
node_js:
- node
cache:
  directories:
   - /website/build
jobs:
  include:
  - stage: Unit tests
    name: Unit Tests Functions
    before_script:
    - cd functions
    - npm i
    script: npm run test:coverage
  - stage: Unit tests
    name: Unit Tests Website
    before_script:
    - cd website
    - npm i
    script: npm run test
  - stage: Build
    if: branch = dev
    name: Build Dev Website
    before_script:
    - cd website
    - npm i
    script: npm run build-dev
    after_success:
      - cd ..
      - sh copy_website.sh
  - stage: Build
    if: branch = master
    name: Build Prod Website
    before_script:
    - cd website
    - npm i
    script: npm run build-prod
  - stage: Deploy
    name: Deploy
    before_script:
      - sh copy_website.sh
      - npm install firebase-tools -g
      - cd functions
      - npm i 
      - cd ..
    script:
      - firebase use --token $FIREBASE_TOKEN $FIREBASE_PROJECT_ID
      - firebase deploy --token $FIREBASE_TOKEN
