sudo: false
branches:
  only:
  - master
  - dev
language: node_js
node_js:
- node
jobs:
  include:
  - stage: Unit tests
    name: Unit Tests Functions
    before_script:
    - cd functions
    - npm i
    script: npm run test:coverage
  - stage: Unit tests
    name: Unit Tests Website
    before_script:
    - cd functions
    - npm i
    script: npm run test
  - stage: Build
    if: branch = dev
    name: Build Dev Website
    before_script:
    - cd website
    - npm i
    script: npm run build-dev
    after_success:
      - cd ..
      - sh copy_website.sh
  - stage: Build
    if: branch = master
    name: Build Prod Website
    before_script:
    - cd website
    - npm i
    script: npm run build-prod
    after_success:
      - cd ..
      - sh copy_website.sh
  - stage: Deploy
    name: Deploy Dev
    if: branch = dev
    deploy:
      on:
        branch: dev
      project: "dev-feedmyflow"
      provider: firebase
      edge: true
      token:
        secure: PwUqqajY6DbzkslJt7ZqAPJ7SdkDY+bb7Gb5FEVF1qIQhg6bgBQgaPYurwNC+s4skniarsrr5eOCgzPuNq9U7HYV5hT/kjxnrmftSOYHLz4K3Uta+6xBfklD3rH7YgyU1wtKDV0opUJqHGlAMMeeQcbPTPU9uiNpDBNdqSGC3u4Mll1+acplTQhDXb6FiOw4sB4XchxQCHzwjK+3oAuoDRZAsaFxfedrqnZ5f3/d6e94R2f6fFQzBv8+XvXHzCs0A8pkVOKXGlnDsk8VQtdcInoYq4nncTpMHAWGQhtO/Hu4aIzT+FdA8WVFSCmoBP0QNkTbbhAv8MIh+os3HpLZSnFlP0lwqJVlEvq+coe0iWGqfm9mY19HTvXMJtn7+SqOKg4b1pL7gt1rA+oEyIAUKZ0omhpxbg3LDzggmginp42DvPomAk1xDaUCSrcIvjOi0j9hFkSpc9/QOfz+UYgWTDAux9pTpSsbCk5RyGCgaU2bm0Fke+vHfaOCXKaO/+AagSiwzaDKdiioPR2+iCr6fAGRne6wyw1e1E5MeaJMXaoPINeDfvNNFcbCoTPf7rdBp1k8feLSJ9qNYWyzBMPXuS8iOCcfTQyoNIkDl7YkwaGV9nAZ4KEkhovjRb92ZyRf+2XJmpvRqBzum3ts9PCALpX2yphZFlu5WE6X8pJWhrk=
  - stage: Deploy
    name: Deploy Prod
    if: branch = master
    deploy:
      on:
        branch: master
      project: "feedmyflow"
      provider: firebase
      edge: true
      token:
        secure: DjKhUt3etCF4cTp4jFuODcDLepg785drC2FwDqjcwn+pJATanfgDupvAVG6OQxDja4AiGPscwjuZ6W/wDVcyw65ARyPi9pqAvseXA8wB5s/V0rNmRvkByjCyqP9/GUawfVdTk/qPqThIHI4ZQCeN67vtGpIvDzemu4RtYD9BYqS060JgqntyXtkRTRx9G2dAQsQ7us4DxLfP0G76s1OiVA7tI8yLtc8RlVCmjaRqVV+3HC5mGt3EUimrdtaFgmltuP/WUUKtqy1SjtSIDKa+VapXChL0wnW65mPGqaRk0Wb3pOo4/QlrAf2+t4MhTj2pvYzHLvMX+R/LAQYHgP+QsW/V2Js0JaSfg5QaRfdWlNxZAzirox7Wc8kSOmI5m9M8Prx/5ofa1nExmzGQP9wGWB4E8LNtMSzUJ38heQPf448iqsfnYvKvavar4zyu+hUu8Dnt7UK0fQZXBfrL3H1JNV+zc7YxQiEbhGRdHSygcYcMRDsOoXTQjIQLa41ohk6A3sGXzC7b3Q3fD/aTRO0Tu4ikeYWtP7JxxxblP4YmVg/eWcjyEqDXT/UzEO9XI2IFT3a8JRiguNtpQZqhtgT5jFWSUMYNKRvxZkxyCVTgrSY9e613MxdGAYkL8gyBF/iDUgxf5rEjgfs1ve7xBOmyGou87SK/oHAAdfFq6XuuFAI=
