sudo: true
branches:
  only:
  - master
  - dev
language: node_js
node_js:
- node
cache:
  directories:
   - /public/
   - /functions/node_modules/
   - /website/node_modules/
jobs:
  include:
  - stage: Unit tests
    name: Unit Tests Functions
    before_script:
    - cd functions
    - npm i
    script: npm run test:coverage
  - stage: Unit tests
    name: Unit Tests Website
    before_script:
    - cd website
    - npm i
    script: npm run test
  - stage: Build
    if: branch = dev
    name: Build Dev Website
    before_script:
    - cd website
    - npm i
    script: npm run build-dev
    after_success:
      - cd ..
      - sh copy_website.sh
  - stage: Build
    if: branch = master
    name: Build Prod Website
    before_script:
    - cd website
    - npm i
    script: npm run build-prod
    after_success:
      - cd ..
      - sh copy_website.sh
  - stage: Deploy
    name: Deploy Dev
    if: branch = dev
    before_script:
      - npm install firebase-tools -g
    script:
      - firebase use --token $FIREBASE_TOKEN $FIREBASE_PROJECT_ID
      - firebase deploy --token $FIREBASE_TOKEN
  - stage: Deploy
      name: Deploy Prod
      if: branch = master
      before_script:
        - npm install firebase-tools -g
      script:
        - firebase use --token $FIREBASE_TOKEN $FIREBASE_PROJECT_ID
        - firebase deploy --token $FIREBASE_TOKEN
  
